/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package sistemaactivos.presentation.bien;

import java.util.Observable;
import sistemaactivos.SistemaActivos;
import sistemaactivos.logic.Bien;

/**
 *
 * @author CarlosAndrés
 */
public class ViewBien extends javax.swing.JDialog implements java.util.Observer {

    ControllerBien controller;
    ModelBien model;

    
    
    /**
     * Creates new form ViewBien
     */
    public ViewBien(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

       public ModelBien getModel() {
        return model;
    }

    public void setModel(ModelBien model) {
        this.model = model;
        model.addObserver(this);
    }

    public ControllerBien getController() {
        return controller;
    }
    
    public void setController(ControllerBien controller) {
        this.controller = controller;
    }
    
    Bien toBien() {
        Bien result = new Bien();
        result.setSerial(this.serialjTextField.getText());
        result.setMarca(this.MarcajTextField.getText());
        result.setDecripcion(this.descripcionjTextField.getText());
        result.setModelo(this.ModelojTextField.getText());
        result.setPrecioUnitario(Integer.getInteger(this.PrecioUnitariojTextField.getText()));
        result.setCantidad(Integer.getInteger(this.CantidadjTextField.getText()));
        return result;
        
    }
    
     public void limpiarErrores() {
        this.SerialjLabel.setForeground(SistemaActivos.COLOR_OK);
         this.DescripciónjLabel.setForeground(SistemaActivos.COLOR_OK);
         this.MarcajLabel.setForeground(SistemaActivos.COLOR_OK);
         this.ModelojLabel.setForeground(SistemaActivos.COLOR_OK);
         this.PrecioUnitariojLabel.setForeground(SistemaActivos.COLOR_OK);
        this.CantidadjLabel1.setForeground(SistemaActivos.COLOR_OK);
        this.CantidadjLabel1.setForeground(SistemaActivos.COLOR_OK);
         }

    
    boolean validar(){
        boolean error= false;
        this.CategoriajLabel.setForeground(SistemaActivos.COLOR_OK);
        if(this.categoriajComboBox1.getSelectedIndex() == -1){
         this.CategoriajLabel.setForeground(SistemaActivos.COLOR_ERROR);
         error=true;
        }
   
    return !error;
    }
    
    
    
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        procesarjButton = new javax.swing.JButton();
        SerialjLabel = new javax.swing.JLabel();
        serialjTextField = new javax.swing.JTextField();
        CategoriajLabel = new javax.swing.JLabel();
        DescripciónjLabel = new javax.swing.JLabel();
        descripcionjTextField = new javax.swing.JTextField();
        MarcajLabel = new javax.swing.JLabel();
        MarcajTextField = new javax.swing.JTextField();
        ModelojLabel = new javax.swing.JLabel();
        ModelojTextField = new javax.swing.JTextField();
        PrecioUnitariojLabel = new javax.swing.JLabel();
        PrecioUnitariojTextField = new javax.swing.JTextField();
        CantidadjLabel1 = new javax.swing.JLabel();
        CantidadjTextField = new javax.swing.JTextField();
        categoriajComboBox1 = new javax.swing.JComboBox<>();
        salirjButton = new javax.swing.JButton();

        setTitle("Bien");

        procesarjButton.setText("Procesar");
        procesarjButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                procesarjButtonActionPerformed(evt);
            }
        });

        SerialjLabel.setText("Serial");

        serialjTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                serialjTextFieldActionPerformed(evt);
            }
        });

        CategoriajLabel.setText("Categoria");

        DescripciónjLabel.setText("Descripción");

        MarcajLabel.setText("Marca");

        ModelojLabel.setText("Modelo");

        PrecioUnitariojLabel.setText("Precio Unitario");

        CantidadjLabel1.setText("Cantidad");

        categoriajComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        salirjButton.setText("salir");
        salirjButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                salirjButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(CategoriajLabel)
                                .addGap(40, 40, 40)
                                .addComponent(categoriajComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(86, 86, 86))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(MarcajLabel)
                                        .addComponent(DescripciónjLabel)
                                        .addComponent(SerialjLabel)
                                        .addComponent(ModelojLabel))
                                    .addGap(33, 33, 33)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(descripcionjTextField, javax.swing.GroupLayout.DEFAULT_SIZE, 106, Short.MAX_VALUE)
                                        .addComponent(serialjTextField)
                                        .addComponent(MarcajTextField)
                                        .addComponent(ModelojTextField)))
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(PrecioUnitariojLabel)
                                        .addComponent(CantidadjLabel1))
                                    .addGap(18, 18, 18)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(PrecioUnitariojTextField)
                                        .addComponent(CantidadjTextField))))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(41, 41, 41)
                        .addComponent(procesarjButton)
                        .addGap(48, 48, 48)
                        .addComponent(salirjButton)))
                .addContainerGap(47, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(47, 47, 47)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(SerialjLabel)
                    .addComponent(serialjTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(DescripciónjLabel)
                    .addComponent(descripcionjTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(MarcajLabel)
                    .addComponent(MarcajTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(ModelojLabel)
                    .addComponent(ModelojTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(PrecioUnitariojLabel)
                    .addComponent(PrecioUnitariojTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(CantidadjLabel1)
                    .addComponent(CantidadjTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(CategoriajLabel)
                    .addComponent(categoriajComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(procesarjButton)
                    .addComponent(salirjButton))
                .addGap(0, 34, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void serialjTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_serialjTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_serialjTextFieldActionPerformed

    private void procesarjButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_procesarjButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_procesarjButtonActionPerformed

    private void salirjButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_salirjButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_salirjButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel CantidadjLabel1;
    private javax.swing.JTextField CantidadjTextField;
    private javax.swing.JLabel CategoriajLabel;
    private javax.swing.JLabel DescripciónjLabel;
    private javax.swing.JLabel MarcajLabel;
    private javax.swing.JTextField MarcajTextField;
    private javax.swing.JLabel ModelojLabel;
    private javax.swing.JTextField ModelojTextField;
    private javax.swing.JLabel PrecioUnitariojLabel;
    private javax.swing.JTextField PrecioUnitariojTextField;
    private javax.swing.JLabel SerialjLabel;
    private javax.swing.JComboBox<String> categoriajComboBox1;
    private javax.swing.JTextField descripcionjTextField;
    private javax.swing.JButton procesarjButton;
    private javax.swing.JButton salirjButton;
    private javax.swing.JTextField serialjTextField;
    // End of variables declaration//GEN-END:variables

    @Override
    public void update(Observable o, Object arg) {
       this.limpiarErrores();
        Bien actual = model.getCurrent();
        this.fromBien(actual);
     }

   public void fromBien(Bien actual) {
        
       this.serialjTextField.setText(actual.getSerial().toString());
       this.serialjTextField.setEnabled(false);
       Boolean modify = model.getModo() == SistemaActivos.MODO_EDITAR;

       
         this.descripcionjTextField.setEnabled(!modify);
        descripcionjTextField.setText(actual.getDecripcion());

        this.MarcajTextField.setEnabled(!modify);
        MarcajTextField.setText(actual.getMarca());

        this.ModelojTextField.setEnabled(!modify);
        ModelojTextField.setText(actual.getModelo());
        
         this.PrecioUnitariojTextField.setEditable(!modify);
        PrecioUnitariojTextField.setText(Double.toString(actual.getPrecioUnitario()));

         this.CantidadjTextField.setEditable(!modify);
         CantidadjTextField.setText(Integer.toString(actual.getCantidad()));
        
         
         this.categoriajComboBox1.setEditable(modify);
        //hacer metodo para cargar un arrayList de objetos categoria en lo que 
        //va a sacar las descripciones que van en los indeces del comboBox
      
        
        
        
        
        procesarjButton.setVisible(modify);
        this.validate();
    }


}
