-- MySQL Script generated by MySQL Workbench
-- Mon Oct 22 21:22:17 2018
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema SistemaActivos
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema SistemaActivos
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `SistemaActivos` DEFAULT CHARACTER SET utf8 ;
USE `SistemaActivos` ;

-- -----------------------------------------------------
-- Table `SistemaActivos`.`Dependencia`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `SistemaActivos`.`Dependencia` (
  `codigo` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`codigo`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `SistemaActivos`.`Funcionario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `SistemaActivos`.`Funcionario` (
  `id` VARCHAR(42) NOT NULL,
  `nombre` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `SistemaActivos`.`Solicitud`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `SistemaActivos`.`Solicitud` (
  `numSolicitud` INT NOT NULL AUTO_INCREMENT,
  `numComprobante` INT NOT NULL,
  `fecha` DATE NOT NULL,
  `tipoAdquisicion` VARCHAR(45) NOT NULL,
  `cantidadBienes` INT NOT NULL,
  `montoTotal` DOUBLE NOT NULL,
  `razonRechazo` VARCHAR(45) NOT NULL,
  `estado` VARCHAR(45) NOT NULL,
  `dependenciaSolicitud` INT NOT NULL,
  `funcionarioSolicitud` VARCHAR(42) NULL,
  PRIMARY KEY (`numSolicitud`),
  INDEX `llaveDependenciaSolicitud` (`dependenciaSolicitud` ASC),
  INDEX `llaveFuncionarioSolicitud` (`funcionarioSolicitud` ASC),
  CONSTRAINT `dependenciaSolicitud`
    FOREIGN KEY (`dependenciaSolicitud`)
    REFERENCES `SistemaActivos`.`Dependencia` (`codigo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `funcionarioSolicitud`
    FOREIGN KEY (`funcionarioSolicitud`)
    REFERENCES `SistemaActivos`.`Funcionario` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `SistemaActivos`.`Categoria`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `SistemaActivos`.`Categoria` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `incremento` INT NOT NULL,
  `descripcion` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `SistemaActivos`.`Bien`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `SistemaActivos`.`Bien` (
  `serial` VARCHAR(25) NOT NULL,
  `decripcion` VARCHAR(45) NOT NULL,
  `marca` VARCHAR(45) NOT NULL,
  `modelo` VARCHAR(45) NOT NULL,
  `precioUnitario` DOUBLE NOT NULL,
  `solicitudBien` INT NOT NULL,
  `categoriaBien` INT NULL,
  `cantidad` INT NOT NULL,
  INDEX `llaveSolicitudBien` (`solicitudBien` ASC),
  INDEX `llaveCategoriaBien` (`categoriaBien` ASC),
  PRIMARY KEY (`serial`),
  CONSTRAINT `solicitudBien`
    FOREIGN KEY (`solicitudBien`)
    REFERENCES `SistemaActivos`.`Solicitud` (`numSolicitud`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `CategoriaBien`
    FOREIGN KEY (`categoriaBien`)
    REFERENCES `SistemaActivos`.`Categoria` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `SistemaActivos`.`Puesto`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `SistemaActivos`.`Puesto` (
  `codigo` INT NOT NULL,
  `puesto` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`codigo`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `SistemaActivos`.`Labor`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `SistemaActivos`.`Labor` (
  `dependenciaLabor` INT NOT NULL,
  `FuncionarioLabor` VARCHAR(42) NOT NULL,
  `PuestoLabor` INT NOT NULL,
  PRIMARY KEY (`dependenciaLabor`, `FuncionarioLabor`, `PuestoLabor`),
  INDEX `llaveDependenciaLabor` (`dependenciaLabor` ASC),
  INDEX `llaveFuncionarioLabor` (`FuncionarioLabor` ASC),
  INDEX `llavePuestoLabor` (`PuestoLabor` ASC),
  CONSTRAINT `dependenciaLabor`
    FOREIGN KEY (`dependenciaLabor`)
    REFERENCES `SistemaActivos`.`Dependencia` (`codigo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `funcionarioLabor`
    FOREIGN KEY (`FuncionarioLabor`)
    REFERENCES `SistemaActivos`.`Funcionario` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `puestoLabor`
    FOREIGN KEY (`PuestoLabor`)
    REFERENCES `SistemaActivos`.`Puesto` (`codigo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `SistemaActivos`.`Activo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `SistemaActivos`.`Activo` (
  `codigoId` VARCHAR(45) NOT NULL,
  `bienActivo` VARCHAR(25) NOT NULL,
  `dependenciaActivo` INT NULL,
  `FuncionarioActivo` VARCHAR(42) NULL,
  `PuestoActivo` INT NULL,
  PRIMARY KEY (`codigoId`),
  INDEX `llaveBienActivo` (`bienActivo` ASC),
  INDEX `llaveLaborActivo` (`dependenciaActivo` ASC, `FuncionarioActivo` ASC, `PuestoActivo` ASC),
  CONSTRAINT `bienActivo`
    FOREIGN KEY (`bienActivo`)
    REFERENCES `SistemaActivos`.`Bien` (`serial`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `laborActivo`
    FOREIGN KEY (`dependenciaActivo` , `FuncionarioActivo` , `PuestoActivo`)
    REFERENCES `SistemaActivos`.`Labor` (`dependenciaLabor` , `FuncionarioLabor` , `PuestoLabor`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `SistemaActivos`.`Usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `SistemaActivos`.`Usuario` (
  `id` VARCHAR(45) NOT NULL,
  `pass` VARCHAR(45) NOT NULL,
  `funcionarioUsuario` VARCHAR(42) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `llaveFuncionarioUsuario` (`funcionarioUsuario` ASC),
  CONSTRAINT `funcionarioUsuario`
    FOREIGN KEY (`funcionarioUsuario`)
    REFERENCES `SistemaActivos`.`Funcionario` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
