/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package sistemaactivos.presentation.solicitud.edicion;

import java.util.HashSet;
import java.util.Observable;
import sistemaactivos.SistemaActivos;
import sistemaactivos.logic.Bien;
import sistemaactivos.logic.Solicitud;

/**
 *
 * @author ExtremeTech
 */
public class ViewSolicitudEdicion extends javax.swing.JDialog implements java.util.Observer {

    ControllerSolicitudEdicion controller;
    ModelSolicitudEdicion model;

    /**
     * Creates new form viewSolicitudEdicion
     */
    public ViewSolicitudEdicion(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

    public ModelSolicitudEdicion getModel() {
        return model;
    }

    public void setModel(ModelSolicitudEdicion model) {
        this.model = model;
        model.addObserver(this);
    }

    public ControllerSolicitudEdicion getController() {
        return controller;
    }

    public void setController(ControllerSolicitudEdicion controller) {
        this.controller = controller;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        guardar = new javax.swing.JButton();
        salir = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        snumsol = new javax.swing.JLabel();
        numcomp = new javax.swing.JLabel();
        fec = new javax.swing.JLabel();
        tipadq = new javax.swing.JLabel();
        fecha = new com.toedter.calendar.JDateChooser();
        numSolicitud = new javax.swing.JTextField();
        numcomprobante = new javax.swing.JTextField();
        tipoadq = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        estadoactual = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        cantidadbienes = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        montototal = new javax.swing.JTextField();
        rechazo = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        razon = new javax.swing.JTextArea();
        jLabel2 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        Lserial = new javax.swing.JLabel();
        serial = new javax.swing.JTextField();
        Lmarca = new javax.swing.JLabel();
        marca = new javax.swing.JTextField();
        Ldescripcion = new javax.swing.JLabel();
        descripcion = new javax.swing.JTextField();
        Lmodelo = new javax.swing.JLabel();
        modelo = new javax.swing.JTextField();
        LprecioU = new javax.swing.JLabel();
        precioUnidad = new javax.swing.JTextField();
        Lcantidad = new javax.swing.JLabel();
        cantbien = new javax.swing.JTextField();
        agregarbien = new javax.swing.JButton();
        eliminarbien = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        bient = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablabienes = new javax.swing.JTable();

        setTitle("SOLICITUD");

        guardar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sistemaactivos/presentation/icons/iconguardar.png"))); // NOI18N
        guardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                guardarActionPerformed(evt);
            }
        });

        salir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sistemaactivos/presentation/icons/iconsalir.png"))); // NOI18N
        salir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                salirActionPerformed(evt);
            }
        });

        jPanel1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        snumsol.setText("Número de solicitud ");

        numcomp.setText("Número de comprobante ");

        fec.setText("Fecha de adquisición");

        tipadq.setText("Tipo de adquisición");

        fecha.setToolTipText("");

        jLabel6.setText("Estado: ");

        estadoactual.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Solicitando", "Recibida", "Por Verificar", "Rechazada", "Aceptada", "Incorporacion", "En espera de rotulación", "Asignacion responsable y dependencia", "Procesada" }));

        jLabel4.setText("Cantidad de bienes");

        jLabel5.setText("Monto total");

        rechazo.setText("Razon de Rechazo");

        razon.setColumns(20);
        razon.setRows(5);
        jScrollPane2.setViewportView(razon);

        jLabel2.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jLabel2.setText("Datos de la Solicitud");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jScrollPane2)
                        .addContainerGap())
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(snumsol)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(numSolicitud, javax.swing.GroupLayout.PREFERRED_SIZE, 267, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(numcomp)
                                    .addComponent(fec)
                                    .addComponent(tipadq)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel5))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(montototal, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(cantidadbienes, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(fecha, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(numcomprobante, javax.swing.GroupLayout.PREFERRED_SIZE, 267, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addComponent(tipoadq, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 267, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                        .addContainerGap())
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(estadoactual, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(60, 60, 60))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(rechazo)
                        .addGap(0, 0, Short.MAX_VALUE))))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(136, 136, 136)
                .addComponent(jLabel2)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addGap(16, 16, 16)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(snumsol)
                    .addComponent(numSolicitud, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(numcomp, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(numcomprobante, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(fec)
                    .addComponent(fecha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(tipadq)
                    .addComponent(tipoadq, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(3, 3, 3)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(cantidadbienes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(3, 3, 3)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(montototal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6)
                    .addComponent(estadoactual, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(rechazo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel2.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        Lserial.setText("Serial");

        Lmarca.setText("Marca");

        Ldescripcion.setText("Descripcion");

        Lmodelo.setText("Modelo");

        LprecioU.setText("Precio Unitario");

        Lcantidad.setText("Cantidad");

        agregarbien.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sistemaactivos/presentation/icons/iconagregararchivo.png"))); // NOI18N
        agregarbien.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                agregarbienActionPerformed(evt);
            }
        });

        eliminarbien.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sistemaactivos/presentation/icons/iconeliminar.png"))); // NOI18N
        eliminarbien.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                eliminarbienActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jLabel1.setText("Gestion de Bienes");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(Ldescripcion)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addComponent(Lserial)
                                        .addGap(54, 54, 54)
                                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(serial, javax.swing.GroupLayout.PREFERRED_SIZE, 229, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(92, 92, 92)
                                .addComponent(agregarbien, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(34, 34, 34)
                                .addComponent(eliminarbien, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                .addComponent(Lcantidad)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(cantbien, javax.swing.GroupLayout.PREFERRED_SIZE, 227, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(LprecioU)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(precioUnidad, javax.swing.GroupLayout.PREFERRED_SIZE, 227, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                .addComponent(Lmodelo)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(modelo, javax.swing.GroupLayout.PREFERRED_SIZE, 227, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(descripcion, javax.swing.GroupLayout.PREFERRED_SIZE, 308, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                .addComponent(Lmarca)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(marca, javax.swing.GroupLayout.PREFERRED_SIZE, 229, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(serial, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Lserial))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(marca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Lmarca))
                .addGap(4, 4, 4)
                .addComponent(Ldescripcion)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(descripcion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(modelo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Lmodelo))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LprecioU)
                    .addComponent(precioUnidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cantbien, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Lcantidad))
                .addGap(28, 28, 28)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(agregarbien)
                    .addComponent(eliminarbien))
                .addGap(31, 31, 31))
        );

        jPanel3.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        bient.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        bient.setText("Bienes Inmuebles");

        tablabienes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tablabienes);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addComponent(bient)
                        .addGap(310, 310, 310))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 745, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(bient)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(329, 329, 329)
                        .addComponent(guardar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(salir)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(15, 15, 15)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(guardar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(salir, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void guardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_guardarActionPerformed
        if(validar()){
            
        }
    }//GEN-LAST:event_guardarActionPerformed

    private void salirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_salirActionPerformed
        //cancelar
    }//GEN-LAST:event_salirActionPerformed

    private void agregarbienActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_agregarbienActionPerformed
        //Agregar un bien 
    }//GEN-LAST:event_agregarbienActionPerformed

    private void eliminarbienActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eliminarbienActionPerformed
//Eliminar un bien selecionado
    }//GEN-LAST:event_eliminarbienActionPerformed

    Solicitud toSolicitud() {
        Solicitud result = new Solicitud();
        result.setNumComprobante(Integer.getInteger(numcomprobante.getText()));
        result.setFecha(fecha.getDate());
        result.setTipoAdquisicion(tipoadq.getText());
        result.setBiens(new HashSet<>(model.bientable.getRows()));
        result.setCantidadBienes(Integer.getInteger(cantidadbienes.getText()));
        result.setMontoTotal(Integer.getInteger(montototal.getText()));
        result.setEstado(estadoactual.getSelectedItem().toString());
        result.setRazonRechazo(razon.getText());
        return result;
    }

    Bien toBien() {
        Bien result = new Bien();
        result.setSerial(this.serial.getText());
        result.setMarca(this.marca.getText());
        result.setDecripcion(this.descripcion.getText());
        result.setModelo(this.modelo.getText());
        result.setPrecioUnitario(Integer.getInteger(this.precioUnidad.getText()));
        result.setCantidad(Integer.getInteger(this.cantbien.getText()));
        return result;
    }

    public void limpiarErrores() {
        this.numcomp.setForeground(SistemaActivos.COLOR_OK);
        this.fec.setForeground(SistemaActivos.COLOR_OK);
        this.tipadq.setForeground(SistemaActivos.COLOR_OK);
        this.bient.setForeground(SistemaActivos.COLOR_OK);
        this.rechazo.setForeground(SistemaActivos.COLOR_OK);
        this.Lcantidad.setForeground(SistemaActivos.COLOR_OK);
        this.Ldescripcion.setForeground(SistemaActivos.COLOR_OK);
        this.Lmarca.setForeground(SistemaActivos.COLOR_OK);
        this.Lmodelo.setForeground(SistemaActivos.COLOR_OK);
        this.LprecioU.setForeground(SistemaActivos.COLOR_OK);
        this.Lserial.setForeground(SistemaActivos.COLOR_OK);
    }

    boolean validar() {
        boolean error = false;
        this.numcomp.setForeground(SistemaActivos.COLOR_OK);
        if (this.numcomprobante.getText().isEmpty()) {
            this.numcomp.setForeground(SistemaActivos.COLOR_ERROR);
            error = true;
        }

        this.fec.setForeground(SistemaActivos.COLOR_OK);
        if (this.fecha.getDate() == null) {
            this.fec.setForeground(SistemaActivos.COLOR_ERROR);
            error = true;
        }

        this.tipadq.setForeground(SistemaActivos.COLOR_OK);
        if (this.tipoadq.getText().isEmpty()) {
            this.tipadq.setForeground(SistemaActivos.COLOR_ERROR);
            error = true;
        }

        this.bient.setForeground(SistemaActivos.COLOR_OK);
        if (model.bientable.rows.isEmpty()) {
            this.bient.setForeground(SistemaActivos.COLOR_ERROR);
            error = true;
        }

        this.rechazo.setForeground(SistemaActivos.COLOR_OK);
        if (this.razon.getText().isEmpty() && "Procesada".equals(estadoactual.getSelectedItem().toString())) {
            this.rechazo.setForeground(SistemaActivos.COLOR_ERROR);
            error = true;
        }
        return !error;
    }

    boolean validarBien() {
        boolean error = false;
        this.Lcantidad.setForeground(SistemaActivos.COLOR_OK);
        if (this.cantbien.getText().isEmpty()) {
            this.Lcantidad.setForeground(SistemaActivos.COLOR_ERROR);
            error = true;
        }
        try {
            Integer.parseInt(this.cantbien.getText());
        } catch (NumberFormatException e) {
            this.Lcantidad.setForeground(SistemaActivos.COLOR_ERROR);
            error = true;
        }

        this.Ldescripcion.setForeground(SistemaActivos.COLOR_OK);
        if (this.descripcion.getText().isEmpty()) {
            this.Ldescripcion.setForeground(SistemaActivos.COLOR_ERROR);
            error = true;
        }

        this.Lmarca.setForeground(SistemaActivos.COLOR_OK);
        if (this.marca.getText().isEmpty()) {
            this.Lmarca.setForeground(SistemaActivos.COLOR_ERROR);
            error = true;
        }

        this.Lmodelo.setForeground(SistemaActivos.COLOR_OK);
        if (this.modelo.getText().isEmpty()) {
            this.Lmodelo.setForeground(SistemaActivos.COLOR_ERROR);
            error = true;
        }

        this.LprecioU.setForeground(SistemaActivos.COLOR_OK);
        if (this.precioUnidad.getText().isEmpty()) {
            this.LprecioU.setForeground(SistemaActivos.COLOR_ERROR);
            error = true;
        }
        try {
            Double.parseDouble(this.precioUnidad.getText());
        } catch (NumberFormatException e) {
            this.LprecioU.setForeground(SistemaActivos.COLOR_ERROR);
            error = true;
        }

        this.Lserial.setForeground(SistemaActivos.COLOR_OK);
        if (this.serial.getText().isEmpty()) {
            this.Lserial.setForeground(SistemaActivos.COLOR_ERROR);
            error = true;
        }
        try {
            Integer.parseInt(this.serial.getText());
        } catch (NumberFormatException e) {
            this.Lserial.setForeground(SistemaActivos.COLOR_ERROR);
            error = true;
        }
        return !error;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Lcantidad;
    private javax.swing.JLabel Ldescripcion;
    private javax.swing.JLabel Lmarca;
    private javax.swing.JLabel Lmodelo;
    private javax.swing.JLabel LprecioU;
    private javax.swing.JLabel Lserial;
    private javax.swing.JButton agregarbien;
    private javax.swing.JLabel bient;
    private javax.swing.JTextField cantbien;
    private javax.swing.JTextField cantidadbienes;
    private javax.swing.JTextField descripcion;
    private javax.swing.JButton eliminarbien;
    private javax.swing.JComboBox<String> estadoactual;
    private javax.swing.JLabel fec;
    private com.toedter.calendar.JDateChooser fecha;
    private javax.swing.JButton guardar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextField marca;
    private javax.swing.JTextField modelo;
    private javax.swing.JTextField montototal;
    private javax.swing.JTextField numSolicitud;
    private javax.swing.JLabel numcomp;
    private javax.swing.JTextField numcomprobante;
    private javax.swing.JTextField precioUnidad;
    private javax.swing.JTextArea razon;
    private javax.swing.JLabel rechazo;
    private javax.swing.JButton salir;
    private javax.swing.JTextField serial;
    private javax.swing.JLabel snumsol;
    private javax.swing.JTable tablabienes;
    private javax.swing.JLabel tipadq;
    private javax.swing.JTextField tipoadq;
    // End of variables declaration//GEN-END:variables

    @ Override
    public void update(Observable o, Object arg) {
        this.limpiarErrores();
        Solicitud actual = model.getCurrent();
        this.fromSolicitud(actual);
        tablabienes.setModel(model.getBientable());
    }

    public void fromSolicitud(Solicitud actual) {
        this.numSolicitud.setEnabled(false);
        this.numSolicitud.setText(actual.getNumSolicitud().toString());
        Boolean add = model.getModo() == SistemaActivos.MODO_AGREGAR;
        Boolean modify = model.getModo() == SistemaActivos.MODO_EDITAR;

        this.numcomprobante.setEnabled(add);
        numcomprobante.setText(Integer.toString(actual.getNumComprobante()));

        this.fecha.setEnabled(add);
        fecha.setDate(actual.getFecha());

        this.tipoadq.setEnabled(add);
        tipoadq.setText(actual.getTipoAdquisicion());

        this.cantidadbienes.setEditable(false);
        cantidadbienes.setText(Integer.toString(actual.getCantidadBienes()));

        this.montototal.setEditable(false);
        montototal.setText(Double.toString(actual.getMontoTotal()));

        this.estadoactual.setEnabled(modify);
        switch (actual.getEstado()) {
            case "Recibida":
                estadoactual.setSelectedIndex(1);
                break;
            case "Por Verificar":
                estadoactual.setSelectedIndex(2);
                break;
            case "Rechazada":
                estadoactual.setSelectedIndex(3);
                break;
            case "Aceptada":
                estadoactual.setSelectedIndex(4);
                break;
            case "Incorporacion":
                estadoactual.setSelectedIndex(5);
                break;
            case "En espera de rotulación":
                estadoactual.setSelectedIndex(6);
                break;
            case "Asignacion responsable y dependencia":
                estadoactual.setSelectedIndex(7);
                break;
            case "Procesada":
                estadoactual.setSelectedIndex(8);
                break;
            default:
                estadoactual.setSelectedIndex(0);
                break;
        }

        this.razon.setEnabled(modify);
        razon.setText(actual.getRazonRechazo());

        if (!add) {
            this.agregarbien.setVisible(false);
        } else {
            this.agregarbien.setVisible(true);
        }

        if (!add) {
            this.eliminarbien.setVisible(false);
        } else {
            this.eliminarbien.setVisible(true);
        }
        
        this.cantbien.setEnabled(add);
        this.descripcion.setEnabled(add);
        this.marca.setEnabled(add);
        this.modelo.setEnabled(add);
        this.precioUnidad.setEnabled(add);
        this.serial.setEnabled(add);
        
        guardar.setVisible(add);
        this.validate();
    }
}
