/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package sistemaactivos.presentation.aplication;

import java.util.Observable;
import javax.swing.JInternalFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author ExtremeTech
 */
public class ViewAplication extends javax.swing.JFrame implements java.util.Observer {

    ModelAplication model;
    ControllerAplication controller;

    public ModelAplication getModel() {
        return model;
    }

    public void setModel(ModelAplication model) {
        this.model = model;
    }

    public ControllerAplication getController() {
        return controller;
    }

    public void setController(ControllerAplication controller) {
        this.controller = controller;
    }

    public void addInternalFrame(JInternalFrame f) {
        this.desktopPane.add(f);
    }

    /**
     * Creates new form viewAplication
     */
    public ViewAplication() {
        initComponents();
        this.setSize(this.getMaximumSize());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        desktopPane = new javax.swing.JDesktopPane();
        jMenuBar1 = new javax.swing.JMenuBar();
        salirMenu = new javax.swing.JMenu();
        logOut = new javax.swing.JCheckBoxMenuItem();
        DependenciasMenu = new javax.swing.JMenu();
        Dependencias = new javax.swing.JMenuItem();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        Funcionarios = new javax.swing.JMenuItem();
        jMenu4 = new javax.swing.JMenu();
        Solicitudes = new javax.swing.JMenuItem();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenu5 = new javax.swing.JMenu();
        Activos = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem4 = new javax.swing.JMenuItem();
        jMenuItem5 = new javax.swing.JMenuItem();
        ayuda = new javax.swing.JMenu();
        jMenuItem6 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout desktopPaneLayout = new javax.swing.GroupLayout(desktopPane);
        desktopPane.setLayout(desktopPaneLayout);
        desktopPaneLayout.setHorizontalGroup(
            desktopPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 721, Short.MAX_VALUE)
        );
        desktopPaneLayout.setVerticalGroup(
            desktopPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 374, Short.MAX_VALUE)
        );

        salirMenu.setText("Salir");
        salirMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                salirMenuActionPerformed(evt);
            }
        });

        logOut.setSelected(true);
        logOut.setText("LogOut");
        logOut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logOutActionPerformed(evt);
            }
        });
        salirMenu.add(logOut);

        jMenuBar1.add(salirMenu);

        DependenciasMenu.setText("Administrador");

        Dependencias.setText("Listado de Solicitudes");
        Dependencias.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DependenciasActionPerformed(evt);
            }
        });
        DependenciasMenu.add(Dependencias);

        jMenuItem3.setText("Agregar una solicitud");
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        DependenciasMenu.add(jMenuItem3);

        jMenuBar1.add(DependenciasMenu);

        jMenu3.setText("Secretaria OCCB");

        Funcionarios.setText("Listado de solicitudes");
        Funcionarios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FuncionariosActionPerformed(evt);
            }
        });
        jMenu3.add(Funcionarios);

        jMenuBar1.add(jMenu3);

        jMenu4.setText("Jefe de OCCB");

        Solicitudes.setText("Listado de Solicitudes");
        Solicitudes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SolicitudesActionPerformed(evt);
            }
        });
        jMenu4.add(Solicitudes);

        jMenuItem1.setText("Listado de Activos");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu4.add(jMenuItem1);

        jMenuBar1.add(jMenu4);

        jMenu5.setText("Registrador ");

        Activos.setText("Listado de Solicitudes");
        Activos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ActivosActionPerformed(evt);
            }
        });
        jMenu5.add(Activos);

        jMenuItem2.setText("Listado de Activos");
        jMenu5.add(jMenuItem2);

        jMenuBar1.add(jMenu5);

        jMenu1.setText("Jefe de RRHH");

        jMenuItem4.setText("Listado de Funcionarios");
        jMenu1.add(jMenuItem4);

        jMenuItem5.setText("Listado de Dependencias");
        jMenuItem5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem5ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem5);

        jMenuBar1.add(jMenu1);

        ayuda.setText("Ayuda");

        jMenuItem6.setText("Acerca de...");
        jMenuItem6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem6ActionPerformed(evt);
            }
        });
        ayuda.add(jMenuItem6);

        jMenuBar1.add(ayuda);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(desktopPane)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(desktopPane)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void salirMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_salirMenuActionPerformed

        controller.exit();

    }//GEN-LAST:event_salirMenuActionPerformed

    private void logOutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logOutActionPerformed

 controller.exit();
        
    }//GEN-LAST:event_logOutActionPerformed

    private void DependenciasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DependenciasActionPerformed
   controller.dependenciasShow();
   
    }//GEN-LAST:event_DependenciasActionPerformed

    private void FuncionariosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FuncionariosActionPerformed
    
        controller.funcionariosShow();
        
    }//GEN-LAST:event_FuncionariosActionPerformed

    private void SolicitudesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SolicitudesActionPerformed
       controller.solicitudesShow();
    }//GEN-LAST:event_SolicitudesActionPerformed

    private void ActivosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ActivosActionPerformed
        controller.activosShow();
    }//GEN-LAST:event_ActivosActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem3ActionPerformed

    private void jMenuItem5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem5ActionPerformed

    private void jMenuItem6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem6ActionPerformed
        JOptionPane.showMessageDialog(this, "Sistema Activos\n"
                + " Elaborado por:\n "
                + "\tEsteban Espinoza Fallas\n"
                + "\tCarlos Vargas Alfaro\n"
                + "\tDiego Pinto Gómez\n"
                + " Version 1.0", "Acerca de..", JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_jMenuItem6ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem Activos;
    private javax.swing.JMenuItem Dependencias;
    private javax.swing.JMenu DependenciasMenu;
    private javax.swing.JMenuItem Funcionarios;
    private javax.swing.JMenuItem Solicitudes;
    private javax.swing.JMenu ayuda;
    private javax.swing.JDesktopPane desktopPane;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JMenuItem jMenuItem5;
    private javax.swing.JMenuItem jMenuItem6;
    private javax.swing.JCheckBoxMenuItem logOut;
    private javax.swing.JMenu salirMenu;
    // End of variables declaration//GEN-END:variables

    @Override
    public void update(Observable o, Object arg) {
        if (model.getCurrent() != null) {
            this.setTitle("SISTEMA ACTIVOS (" + model.getCurrent().getId() + ")");
        } else {
            this.setTitle("SISTEMA ACTIVOS");
        }
    }
}
