package sistemaactivos.logic;
// Generated 14/10/2018 01:50:32 AM by Hibernate Tools 4.3.1



/**
 * Activo generated by hbm2java
 */
public class Activo  implements java.io.Serializable {


     private String codigoId;
     private Bien bien;
     private Categoria categoria;
     private Labor labor;

    public Activo() {
    }

    public Activo(String codigoId, Bien bien, Categoria categoria, Labor labor) {
       this.codigoId = codigoId;
       this.bien = bien;
       this.categoria = categoria;
       this.labor = labor;
    }
   
    public String getCodigoId() {
        return this.codigoId;
    }
    
    public void setCodigoId(String codigoId) {
        this.codigoId = codigoId;
    }
    public Bien getBien() {
        return this.bien;
    }
    
    public void setBien(Bien bien) {
        this.bien = bien;
    }
    public Categoria getCategoria() {
        return this.categoria;
    }
    
    public void setCategoria(Categoria categoria) {
        this.categoria = categoria;
    }
    public Labor getLabor() {
        return this.labor;
    }
    
    public void setLabor(Labor labor) {
        this.labor = labor;
    }




}


