package sistemaactivos.logic;
// Generated 30/10/2018 04:12:49 AM by Hibernate Tools 4.3.1

import java.util.HashSet;
import java.util.Set;

/**
 * Bien generated by hbm2java
 */
public class Bien implements java.io.Serializable {

    private String serial;
    private Categoria categoria;
    private Solicitud solicitud;
    private String descripcion;
    private String marca;
    private String modelo;
    private double precioU;
    private int cantidad;
    private Set activos = new HashSet(0);

    public Bien() {
        serial = "";
        categoria = new Categoria();
        solicitud = new Solicitud();
        descripcion = "";
        marca = "";
        modelo = "";
        precioU = 0;
        cantidad = 0;
    }

    public Bien(String serial, Solicitud solicitud, String descripcion, String marca, String modelo, double precioU, int cantidad) {
        this.serial = serial;
        this.solicitud = solicitud;
        this.descripcion = descripcion;
        this.marca = marca;
        this.modelo = modelo;
        this.precioU = precioU;
        this.cantidad = cantidad;
    }

    public Bien(String serial, Categoria categoria, Solicitud solicitud, String descripcion, String marca, String modelo, double precioU, int cantidad, Set activos) {
        this.serial = serial;
        this.categoria = categoria;
        this.solicitud = solicitud;
        this.descripcion = descripcion;
        this.marca = marca;
        this.modelo = modelo;
        this.precioU = precioU;
        this.cantidad = cantidad;
        this.activos = activos;
    }

    public String getSerial() {
        return this.serial;
    }

    public void setSerial(String serial) {
        this.serial = serial;
    }

    public Categoria getCategoria() {
        return this.categoria;
    }

    public void setCategoria(Categoria categoria) {
        this.categoria = categoria;
    }

    public Solicitud getSolicitud() {
        return this.solicitud;
    }

    public void setSolicitud(Solicitud solicitud) {
        this.solicitud = solicitud;
    }

    public String getDescripcion() {
        return this.descripcion;
    }

    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }

    public String getMarca() {
        return this.marca;
    }

    public void setMarca(String marca) {
        this.marca = marca;
    }

    public String getModelo() {
        return this.modelo;
    }

    public void setModelo(String modelo) {
        this.modelo = modelo;
    }

    public double getPrecioU() {
        return this.precioU;
    }

    public void setPrecioU(double precioU) {
        this.precioU = precioU;
    }

    public int getCantidad() {
        return this.cantidad;
    }

    public void setCantidad(int cantidad) {
        this.cantidad = cantidad;
    }

    public Set getActivos() {
        return this.activos;
    }

    public void setActivos(Set activos) {
        this.activos = activos;
    }

}
