package sistemaactivos.logic;
// Generated 14/10/2018 01:50:32 AM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Categoria generated by hbm2java
 */
public class Categoria  implements java.io.Serializable {


     private int id;
     private String catergoria;
     private Set activos = new HashSet(0);

    public Categoria() {
    }

	
    public Categoria(int id, String catergoria) {
        this.id = id;
        this.catergoria = catergoria;
    }
    public Categoria(int id, String catergoria, Set activos) {
       this.id = id;
       this.catergoria = catergoria;
       this.activos = activos;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public String getCatergoria() {
        return this.catergoria;
    }
    
    public void setCatergoria(String catergoria) {
        this.catergoria = catergoria;
    }
    public Set getActivos() {
        return this.activos;
    }
    
    public void setActivos(Set activos) {
        this.activos = activos;
    }




}


