package sistemaactivos.logic;
// Generated 17/10/2018 12:42:31 AM by Hibernate Tools 4.3.1


import java.util.ArrayList;
import java.util.List;

/**
 * Dependencia generated by hbm2java
 */
public class Dependencia  implements java.io.Serializable {


     private Integer codigo;
     private String nombre;
     private List labors = new ArrayList<>();
     private List solicituds = new ArrayList<>();

    public Dependencia() {
    }

	
    public Dependencia(String nombre) {
        this.nombre = nombre;
    }
    public Dependencia(String nombre, List labors, List solicituds) {
       this.nombre = nombre;
       this.labors = labors;
       this.solicituds = solicituds;
    }
   
    public Integer getCodigo() {
        return this.codigo;
    }
    
    public void setCodigo(Integer codigo) {
        this.codigo = codigo;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public List getLabors() {
        return this.labors;
    }
    
    public void setLabors(List labors) {
        this.labors = labors;
    }
    public List getSolicituds() {
        return this.solicituds;
    }
    
    public void setSolicituds(List solicituds) {
        this.solicituds = solicituds;
    }




}


