package sistemaactivos.logic;
// Generated 17/10/2018 12:42:31 AM by Hibernate Tools 4.3.1

import java.util.ArrayList;
import java.util.List;

/**
 * Funcionario generated by hbm2java
 */
public class Funcionario implements java.io.Serializable {

    private String id;
    private String nombre;
    private List solicituds = new ArrayList<>();
    private List usuarios = new ArrayList<>();
    private List labors = new ArrayList<>();

    public Funcionario() {
    }

    public Funcionario(String id, String nombre) {
        this.id = id;
        this.nombre = nombre;
    }

    public Funcionario(String id, String nombre, List solicituds, List usuarios, List labors) {
        this.id = id;
        this.nombre = nombre;
        this.solicituds = solicituds;
        this.usuarios = usuarios;
        this.labors = labors;
    }

    public String getId() {
        return this.id;
    }

    public void setId(String id) {
        this.id = id;
    }

    public String getNombre() {
        return this.nombre;
    }

    public void setNombre(String nombre) {
        this.nombre = nombre;
    }

    public List getSolicituds() {
        return this.solicituds;
    }

    public void setSolicituds(List solicituds) {
        this.solicituds = solicituds;
    }

    public List getUsuarios() {
        return this.usuarios;
    }

    public void setUsuarios(List usuarios) {
        this.usuarios = usuarios;
    }

    public List getLabors() {
        return this.labors;
    }

    public void setLabors(List labors) {
        this.labors = labors;
    }

}
