package sistemaactivos.logic;
// Generated 17/10/2018 12:42:31 AM by Hibernate Tools 4.3.1



/**
 * Labor generated by hbm2java
 */
public class Labor  implements java.io.Serializable {


     private LaborId id;
     private Dependencia dependencia;
     private Funcionario funcionario;
     private Puesto puesto;

    public Labor() {
    }

    public Labor(LaborId id, Dependencia dependencia, Funcionario funcionario, Puesto puesto) {
       this.id = id;
       this.dependencia = dependencia;
       this.funcionario = funcionario;
       this.puesto = puesto;
    }
   
    public LaborId getId() {
        return this.id;
    }
    
    public void setId(LaborId id) {
        this.id = id;
    }
    public Dependencia getDependencia() {
        return this.dependencia;
    }
    
    public void setDependencia(Dependencia dependencia) {
        this.dependencia = dependencia;
    }
    public Funcionario getFuncionario() {
        return this.funcionario;
    }
    
    public void setFuncionario(Funcionario funcionario) {
        this.funcionario = funcionario;
    }
    public Puesto getPuesto() {
        return this.puesto;
    }
    
    public void setPuesto(Puesto puesto) {
        this.puesto = puesto;
    }




}


