package sistemaactivos.logic;
// Generated 30/10/2018 02:43:08 AM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Puesto generated by hbm2java
 */
public class Puesto  implements java.io.Serializable {


     private String codgo;
     private String puesto;
     private Set labors = new HashSet(0);

    public Puesto() {
    }

	
    public Puesto(String codgo, String puesto) {
        this.codgo = codgo;
        this.puesto = puesto;
    }
    public Puesto(String codgo, String puesto, Set labors) {
       this.codgo = codgo;
       this.puesto = puesto;
       this.labors = labors;
    }
   
    public String getCodgo() {
        return this.codgo;
    }
    
    public void setCodgo(String codgo) {
        this.codgo = codgo;
    }
    public String getPuesto() {
        return this.puesto;
    }
    
    public void setPuesto(String puesto) {
        this.puesto = puesto;
    }
    public Set getLabors() {
        return this.labors;
    }
    
    public void setLabors(Set labors) {
        this.labors = labors;
    }




}


